name: fitness_admin_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.16+16.1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  drawable_text:
    git:
      url: https://github.com/saedAlHanash/drawable_text
      ref: android


  image_multi_type: ^1.0.5
  m_cubit:
    git:
      url: https://github.com/saedAlHanash/m_cubit

  chat_lib:
    git:
      url: https://github.com/saedAlHanash/chat_lib
#      path: ../../packages/chat_lib

  cupertino_icons: ^1.0.9
  firebase_core: ^4.11.0
  firebase_messaging: ^16.4.1
  flutter_chat_types: ^3.6.2
  cloud_firestore: ^6.6.0
  flutter_chat_ui:
    path: ./packages/flutter_chat_ui-1.6.15

  file_picker: ^11.0.2
  http: ^1.6.0
  image_picker: ^1.2.2
  intl: ^0.20.3
  collection: ^1.19.1
  mime: ^2.0.0
  open_filex: ^4.7.0
  flutter_image_compress: ^2.5.1
  image: ^4.5.4
  path_provider: ^2.1.6
  get_it: ^9.2.1
  shared_preferences: ^2.5.5
  flutter_screenutil: ^5.9.3
  logger: ^2.7.0
  path: ^1.9.1
  flutter_local_notifications: ^22.0.1
  awesome_dialog: ^3.3.0
  url_launcher: ^6.3.2
  flutter_bloc: ^9.1.1
  flutter_sound: ^9.30.0
  just_audio: ^0.10.5
  permission_handler: ^12.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
flutter:

  uses-material-design: true

  assets:
    - assets/Images/
    - assets/seed/live/
    - assets/seed/test/
